stages:
  - build
  - unit-tests
  - integration-tests
  - deploy

variables:
  MAVEN_CLI_OPTS: "-B"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  IMAGE_NAME: "developmentbooks:latest"

cache:
  paths:
    - .m2/repository

# Build stage
build:
  stage: build
  image: maven:3.9.5-eclipse-temurin-21
  tags:
    - maven
  script:
    - mvn $MAVEN_CLI_OPTS clean package -DskipTests

# Unit Tests stage
unit-tests:
  stage: unit-tests
  image: maven:3.9.5-eclipse-temurin-21
  tags:
    - maven
  script:
    - mvn $MAVEN_CLI_OPTS test

# Integration Tests stage
integration-tests:
  stage: integration-tests
  image: maven:3.9.5-eclipse-temurin-21
  tags:
    - maven
  script:
    - echo "Running Integration Tests..."
    - mvn failsafe:integration-test failsafe:verify

# Deploy stage
deploy:
  stage: deploy
  image: docker:20.10.24
  variables:
    DOCKER_HOST: unix:///var/run/docker.sock
  tags:
    - maven
  before_script:
    - docker info
  script:
    - docker build -t $IMAGE_NAME .
    - docker run -d -p 9090:9090 $IMAGE_NAME
